name: very_good_blog_app
description: My new very good Blog app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cache_manager: ^1.0.0+4
  cached_network_image: ^3.2.1
  draggable_home: ^1.0.3
  easy_debounce: ^2.0.2+1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_slidable: ^1.3.0
  flutter_svg: ^1.1.0
  formz: ^0.4.1
  go_router: ^3.1.0
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  json_annotation: ^4.5.0
  phosphor_flutter: ^1.4.0

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.11
  flutter_gen_runner: ^4.3.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

flutter_gen:
  output: lib/app/config/gen/

  integrations:
    flutter_svg: true
