name: very_good_blog_app

on: [pull_request]

defaults:
  run:
    working-directory: ./mobile

jobs:
  build: 
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1      
    with:
      flutter_channel: stable
      flutter_version: 3.0.0
